import { Client, GatewayIntentBits, InteractionType } from 'discord.js';
import {
    joinVoiceChannel,
    createAudioPlayer,
    createAudioResource,
    entersState,
    AudioPlayerStatus,
    VoiceConnectionStatus,
    NoSubscriberBehavior
} from '@discordjs/voice';
import dotenv from 'dotenv';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

// Load env
dotenv.config();

const client = new Client({
    intents: [
        GatewayIntentBits.Guilds,
        GatewayIntentBits.GuildMessages,
        GatewayIntentBits.MessageContent,
        GatewayIntentBits.GuildVoiceStates,
    ],
});

client.once('ready', () => {
    console.log(`Debug Bot Ready! Logged in as ${client.user.tag}`);
    console.log('Invite this bot with correct permissions if you haven\'t already.');
});

client.on('messageCreate', async (message) => {
    if (message.content === '!debugjoin') {
        if (!message.member.voice.channel) {
            return message.reply('Please join a voice channel first!');
        }

        console.log(`Attempting to join channel: ${message.member.voice.channel.name} (${message.member.voice.channel.id})`);

        try {
            const connection = joinVoiceChannel({
                channelId: message.member.voice.channel.id,
                guildId: message.guild.id,
                adapterCreator: message.guild.voiceAdapterCreator,
                selfDeaf: false,
                selfMute: false
            });

            connection.on(VoiceConnectionStatus.Ready, () => {
                console.log('✅ Connection is in the Ready state!');
                message.reply('✅ Successfully connected to voice channel!');
            });

            connection.on(VoiceConnectionStatus.Disconnected, () => {
                console.log('❌ Connection Disconnected');
            });

            connection.on(VoiceConnectionStatus.Signalling, () => {
                console.log('📶 Connection Signalling');
            });

            connection.on(VoiceConnectionStatus.Connecting, () => {
                console.log('🔄 Connection Connecting');
            });

            connection.on('error', (error) => {
                console.error('❌ Connection Error:', error);
                message.reply(`❌ Connection Error: ${error.message}`);
            });

            // Wait for connection to be ready
            try {
                await entersState(connection, VoiceConnectionStatus.Ready, 20_000);
                console.log('✅ Connection stable!');

                // Play a simple beep sound generated by ffmpeg
                // Note: accessing system ffmpeg we installed

            } catch (error) {
                console.error('❌ Failed to join voice channel within 20s:', error);
                message.reply('❌ Failed to join voice channel within 20s. Check console.');
                connection.destroy();
            }

        } catch (error) {
            console.error('❌ Error attempting to join:', error);
            message.reply(`❌ Internal Error: ${error.message}`);
        }
    }
});

client.login(process.env.DISCORD_TOKEN);
